$ANSIBLE_VAULT;1.1;AES256
38346662326632653533386530643337376166626431376639626564643537333861343538643765
6561353161633638613333313735356362626162636137300a633734666638366230653732626131
37353637336437306132643039623630383363343237333032666431353366626561613034346531
3832383962613762620a373664303736363963353761626235613233623165393965316232646363
31633062306333363061356463633565663434316137306232633337353463666564333366363538
66333138333932326665653763353136643138396534376532333730396337363065626131396565
31653035333438303061396136306561353565623063316335303763656630306634326438373333
63373331313735623637306166376134326166653037363734646163336661663231626434613665
63643863373364616436336563656538636132326132386634326261343639343539333132313235
34626431336537393431366334343966396437323635613138346166343962633665346438623130
36613836326334653531363762613731636665323534613631646533303733333033383962343566
32353566393162393962373036393332313035623165343335633432633734376138313432633261
35636462646365303330663737333932383063313565343932313134613030333635653065343032
38613930343635386566633836663338306135663665623764613636326634663263336336363434
37376234636231663833653163313938626166323735363230643337393662363238396531343136
30356666306566303863663630393636376536316534646166663433656637613532613233386437
36393362666236323166363362346161393634353031323139656239353030373539313531333539
3034303133323137353031613239373166653332663461613535
