---
- name: IOS Config Change
  hosts: cisco
  gather_facts: False
  tasks:
    - ios_config:
        provider: "{{ creds_ssh }}"
        lines: "{{ global_config }}"

- name: EOS Config Change
  hosts: arista
  gather_facts: False
  tasks:
    - eos_config:
        provider: "{{ creds_eapi }}"
        lines: "{{ global_config }}"

- name: NXOS Config Change
  hosts: nxos
  gather_facts: False
  tasks:
    - nxos_config:
        provider: "{{ creds_nxapi }}"
        lines: "{{ global_config }}"
