creds_ssh:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"

global_config:
  - "ip domain name {{ default_domain }}"
  - "ip name-server {{ name_server1 }}"
  - "ip name-server {{ name_server2 }}"
  - "ntp server {{ ntp1 }}"
  - "ntp server {{ ntp2 }}"
