---
creds_core:
  hostname: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"

creds_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  dev_os: "ios"
  optional_args: {}
