---
platform: nxos

creds_core_ssh:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  transport: cli
  timeout: 60

creds_core_nxapi:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  transport: nxapi
  use_ssl: yes
  validate_certs: no
  port: 8443
  timeout: 60

creds_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  dev_os: "nxos"
  optional_args:
    port: 8443

vrf_list:
    - red1
    - red2
    - red3
