---
ip_interfaces: 
  - name: Ethernet 2/4
    type: v4
    addr: 10.1.1.1
    remote_addr: 10.1.1.2
    mask: 24
  - name: Ethernet 2/4
    type: v6
    addr: 2001:db8:800:200c::1
    remote_addr: 2001:db8:800:200c::2
    mask: 64
