$ANSIBLE_VAULT;1.1;AES256
36333464353361643239393232353766373431343365353932626535343732306433353162316461
3231626131316239393735643037656164643536643539620a643662343133343066613165346563
36623966303939343633643762383036363233393762646262366264626139306131383738333062
3634376362323563360a346339653830326365306638316532343938666130346330343337623663
63613061313230656531383439323930653233613437316163613964653438663838313662316637
65663235326266343434653131666438313061323135333462363862653265376236613835306231
37343638326565353364356435346664366531333835666533343061643139393330363131656234
34656335623464633630373662323435303232393930313462323839386635333934656233666133
34326337643737323738646637663531336131643830336531656330313263366532313039323736
65336666356264373132656331613761376435616265363237353737373430313530373163333763
39633361313330373030636133356364633563363930383962336663333163653264663732393037
35373436343831666663353939636164326239653161373563316633656136643236306230386462
30643764376633616463636637633761626661333463653934653930366231353733333336366165
38666339386531383663303936333462643037323833326263373936363161313233316437336561
39313161613239326439323434623462646431656537323837646361396636366339383034386635
37393632313732343762323130316534643931623938313332353133323632376562633238663536
62653538653939396333346665356161356632336337333066326464663565326631333739323731
66633033313061396632303239376566396239663137333730356664313435313532366539376232
33313731396439346634353363366638313434343938326461386661343933353632623831343266
66663664636462393164623336646232316331343335366531633766636666633232393535353934
34346534343730656437326431636663643239333664623166366465363361663561366266336437
31383939636461313139613461656136373133626466356264623730366236356265306436666531
63376263356231616136306437393333613865383230656338633931303535306633623339396162
63333634623235643530333861653033653331343133323861633032396161376238333833313533
61353438616162636163396663633931313765303536353132343365393132333630343739373964
61663162346565646166396430326637376131653932303766386166616362656437636437396265
66636233646264636338333238323664393739666230643539353439313461316333373763623132
61646262363830663839
