creds_eapi:
  host: "{{ ansible_host }}"
  username: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  transport: eapi
  use_ssl: True
  validate_certs: no

name_server1: 8.8.8.8
name_server2: 8.8.4.4
default_domain: bogus1.com
ntp1: 130.126.24.24
ntp2: 152.2.21.1

global_config:
  - "ip domain-name {{ default_domain }}"
  - "ip name-server vrf default {{ name_server1 }}"
  - "ip name-server vrf default {{ name_server2 }}"
  - "ntp server {{ ntp1 }}"
  - "ntp server {{ ntp2 }}"
