---
- name: IOS Example
  hosts: pynet-rtr1
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - ios_config:
        provider: "{{ creds }}"
        defaults: True
        lines: 
          - "ip domain lookup"

