---
platform: eos
default_gateway: 10.220.88.1
users:
  - { username: admin, privilege: 15, role: network-admin, secret: $1$aM6w809x$tgkc6ZGhcScvELVKVHq3n0 }
  - { username: admin1, privilege: 15, secret: $1$7kD0oS/t$wXhtTFwnWwnlPFKWwXoJ70 }
  - { username: eapi, secret: "{{ eapi_secret }}" }
  - { username: pyclass, privilege: 15, secret: $1$C3VfUfcO$86t4iqCX60yW.NIR8d2Lh0 }

creds_core_ssh:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: cli
  timeout: 60

creds_core_eapi:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: eapi
  use_ssl: True
  validate_certs: no

creds_napalm:
  hostname: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  dev_os: "eos"
  optional_args: {}

