---

- name: Configure an ACL
  gather_facts: no
  hosts: pynet-rtr1
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
    - name: Configure ACL
      ios_config:
        provider: "{{ creds }}"
        parents: ["ip access-list extended TEST-ACL"]
        lines: 
          - permit ip host 1.1.1.1 any log
          - permit ip host 2.2.2.2 any log
          - permit ip host 3.3.3.3 any log
          - permit ip host 4.4.4.4 any log
        before: ["no ip access-list extended TEST-ACL"]
        replace: line
        match: line
