---
- name: Configure ip-helper on single router
  hosts: cisco:arista
  vars:
    creds:
        host: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"

  tasks:
    - ios_config:
        provider: "{{ creds }}"
        lines:
          - ip helper-address {{ item.helper }}
        parents: interface {{ item.interface }}
      with_items: "{{ dhcp_interfaces }}"

#    - ios_facts:
#        provider: "{{ creds }}"

#    - ios_command:
#        provider: "{{ creds }}"
#        commands: show run
#      register: show_run
#
#    - assert:
#        that: '{{ show_run.stdout[0] | ip_helper | symmetric_difference(dhcp_interfaces) }} == []'
#        msg: "Interface has 'ip helper' configured and shouldn't"
#
